compile:
	# compile it for Linux
	GOOS=linux GOARCH=amd64 go build -o ./bin/hit_linux_amd64
	# compile it for macOS
	GOOS=darwin GOARCH=amd64 go build -o ./bin/hit_darwin_amd64
	# compile it for Apple M1
	GOOS=darwin GOARCH=amd64 go build -o ./bin/hit_darwin_arm
	# compile it for windows
	GOOS=windows GOARCH=amd64 go build -o ./bin/hit_win_amd64
